framework:
    messenger:
        transports:
            async: 
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        routing:
            'App\Message\RemovePairMessage': async
            'App\Message\AddPairMessage': async